# Generated by Django 3.2 on 2022-02-25 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('white', 'White'), ('black', 'Black')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('queen', 'Queen'), ('king', 'King'), ('tower', 'tower'), ('bishop', 'Bishop'), ('pawn', 'Pawn'), ('knight', 'Knight')], max_length=6)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pieces.color')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
